version: '3.9'
services:
  frontend:
    image: node:16.14-alpine
    container_name: NG_frontend-app
    platform: linux/x86_64
    working_dir: /app_frontend
    volumes: 
      - ./frontend:/app_frontend
    tty: true
    stdin_open: true
    command: sh
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000


  backend:
    image: node:16.14-alpine
    container_name: NG_backend-app
    platform: linux/x86_64
    working_dir: /app_backend
    volumes: 
      - ./backend:/app_backend
    tty: true
    stdin_open: true
    command: sh
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      - APP_PORT=3001
      - JWT_SECRET=secretJWT
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_HOST=192.168.160.1
      - DB_PORT=3002
      - DB_NAME=NG_financials


  db:
    image: postgres:13.4-alpine
    container_name: NG_db
    platform: linux/x86_64
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: 'always'
    ports:
      - 3002:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST_AUTH_METHOD=trust

networks:
  default:
    name: NG_default-network
