version: '3.9'
services:
  frontend:
    image: node:16.14-alpine
    container_name: TF_frontend
    platform: linux/x86_64
    working_dir: /app_frontend
    volumes: 
      - ./frontend:/app_frontend
    tty: true
    stdin_open: true
    command: sh
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - front-to-back

  backend:
    image: node:16.14-alpine
    container_name: TF_backend
    platform: linux/x86_64
    working_dir: /app_backend
    volumes: 
      - ./backend:/app_backend
    tty: true
    stdin_open: true
    command: sh
    restart: always
    depends_on:
      - db
    ports:
      - 3001:3001
    networks:
      - front-to-back
      - back-to-db
    environment:
      APP_PORT: 3001
      JWT_SECRET: secretJWT
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: TF_Bank
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres:13.9-alpine
    container_name: TF_db
    platform: linux/x86_64
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
    ports:
      - 3002:5432
    environment:
      POSTGRES_PASSWORD: 123456
    networks:
      - back-to-db
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: TF_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: 123456
    networks:
      - postgres

networks:
  front-to-back: {}
  back-to-db: {}
  postgres:
    driver: bridge
